"""Subscribe model

Revision ID: 6eb181f6b086
Revises: ddc78f231ff9
Create Date: 2022-12-10 09:21:48.057496

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = '6eb181f6b086'
down_revision = 'ddc78f231ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscribers_id'), 'subscribers', ['id'], unique=True)
    op.alter_column('api_keys', 'api_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('example', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('example', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('api_keys', 'api_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_subscribers_id'), table_name='subscribers')
    op.drop_table('subscribers')
    # ### end Alembic commands ###
